# Generated by Django 3.2 on 2022-11-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_short_descriptions_book_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='https://sciendo.com/product-not-found.png', null=True),
        ),
    ]
